// Datos de ejemplo para el modo demo (sin Supabase configurado).
// Mismos campos que la tabla closet_items / outfits del schema.sql.

export const mockItems = [
  {
    id: 1, serial: 'CLUE-DEMO-0001-0001', item_name: 'Blazer negro oversized',
    brand: 'Zara', category: 'outerwear', color: 'negro', material: 'lana',
    pattern: 'liso', fit: 'oversized', condition: 'excelente',
    style_tags: ['minimal', 'formal'], occasion_tags: ['oficina', 'noche'],
    season_tags: ['otoño', 'invierno'], rarity: 4, rarity_label: 'Statement',
    top_speed: 5, acceleration: 4, braking: 5, traction: 3, comfort: 4,
    city_scanned: 'Buenos Aires', date_scanned: 'Jun 12, 2026',
    image_url: '', favorite: true, custom_tags: [], saved_at: 1750000000000,
  },
  {
    id: 2, serial: 'CLUE-DEMO-0002-0002', item_name: 'Remera blanca de algodón',
    brand: '', category: 'top', color: 'blanco', material: 'algodón',
    pattern: 'liso', fit: 'regular', condition: 'buena',
    style_tags: ['básico', 'casual'], occasion_tags: ['diario'],
    season_tags: ['verano', 'primavera'], rarity: 1, rarity_label: 'Basic',
    top_speed: 3, acceleration: 5, braking: 5, traction: 1, comfort: 3,
    city_scanned: 'Buenos Aires', date_scanned: 'Jun 12, 2026',
    image_url: '', favorite: false, custom_tags: [], saved_at: 1750000100000,
  },
  {
    id: 3, serial: 'CLUE-DEMO-0003-0003', item_name: 'Jean recto azul',
    brand: "Levi's", category: 'bottom', color: 'azul', material: 'denim',
    pattern: 'liso', fit: 'recto', condition: 'buena',
    style_tags: ['casual', 'clásico'], occasion_tags: ['diario', 'salidas'],
    season_tags: ['todo el año'], rarity: 2, rarity_label: 'Everyday',
    top_speed: 4, acceleration: 5, braking: 5, traction: 2, comfort: 4,
    city_scanned: 'Buenos Aires', date_scanned: 'Jun 15, 2026',
    image_url: '', favorite: false, custom_tags: [], saved_at: 1750000200000,
  },
  {
    id: 4, serial: 'CLUE-DEMO-0004-0004', item_name: 'Zapatillas blancas',
    brand: 'Nike', category: 'shoes', color: 'blanco', material: 'cuero',
    pattern: 'liso', fit: '', condition: 'muy buena',
    style_tags: ['sporty', 'casual'], occasion_tags: ['diario'],
    season_tags: ['todo el año'], rarity: 2, rarity_label: 'Everyday',
    top_speed: 4, acceleration: 5, braking: 4, traction: 2, comfort: 5,
    city_scanned: 'Buenos Aires', date_scanned: 'Jun 18, 2026',
    image_url: '', favorite: true, custom_tags: [], saved_at: 1750000300000,
  },
  {
    id: 5, serial: 'CLUE-DEMO-0005-0005', item_name: 'Vestido rojo satinado',
    brand: '', category: 'dress', color: 'rojo', material: 'satén',
    pattern: 'liso', fit: 'slip', condition: 'excelente',
    style_tags: ['elegante', 'statement'], occasion_tags: ['fiesta', 'noche'],
    season_tags: ['verano'], rarity: 5, rarity_label: 'Signature',
    top_speed: 5, acceleration: 2, braking: 3, traction: 5, comfort: 4,
    city_scanned: 'Córdoba', date_scanned: 'Jul 1, 2026',
    image_url: '', favorite: true, custom_tags: ['evento'], saved_at: 1750000400000,
  },
  {
    id: 6, serial: 'CLUE-DEMO-0006-0006', item_name: 'Cartera mini negra',
    brand: '', category: 'accessory', color: 'negro', material: 'cuero',
    pattern: 'liso', fit: '', condition: 'buena',
    style_tags: ['elegante', 'minimal'], occasion_tags: ['noche', 'salidas'],
    season_tags: ['todo el año'], rarity: 3, rarity_label: 'Versatile',
    top_speed: 4, acceleration: 4, braking: 4, traction: 3, comfort: 3,
    city_scanned: 'Buenos Aires', date_scanned: 'Jul 2, 2026',
    image_url: '', favorite: false, custom_tags: [], saved_at: 1750000500000,
  },
  {
    id: 7, serial: 'CLUE-DEMO-0007-0007', item_name: 'Buzo gris con capucha',
    brand: 'Adidas', category: 'top', color: 'gris', material: 'algodón frisado',
    pattern: 'liso', fit: 'relaxed', condition: 'buena',
    style_tags: ['sporty', 'streetwear'], occasion_tags: ['diario', 'casa'],
    season_tags: ['otoño', 'invierno'], rarity: 2, rarity_label: 'Everyday',
    top_speed: 4, acceleration: 4, braking: 4, traction: 2, comfort: 5,
    city_scanned: 'Buenos Aires', date_scanned: 'Jul 5, 2026',
    image_url: '', favorite: false, custom_tags: [], saved_at: 1750000600000,
  },
  {
    id: 8, serial: 'CLUE-DEMO-0008-0008', item_name: 'Botas texanas marrones',
    brand: '', category: 'shoes', color: 'marrón', material: 'cuero',
    pattern: 'liso', fit: '', condition: 'muy buena',
    style_tags: ['boho', 'statement'], occasion_tags: ['salidas', 'festival'],
    season_tags: ['otoño'], rarity: 4, rarity_label: 'Statement',
    top_speed: 5, acceleration: 3, braking: 3, traction: 4, comfort: 3,
    city_scanned: 'Mendoza', date_scanned: 'Jul 6, 2026',
    image_url: '', favorite: false, custom_tags: [], saved_at: 1750000700000,
  },
];

export const mockOutfits = [
  {
    id: 1,
    serial_key: 'CLUE-DEMO-0001-0001+CLUE-DEMO-0003-0003+CLUE-DEMO-0004-0004',
    name: 'Blazer negro + Jean recto + Zapas blancas',
    item_serials: ['CLUE-DEMO-0001-0001', 'CLUE-DEMO-0003-0003', 'CLUE-DEMO-0004-0004'],
    item_names: ['Blazer negro oversized', 'Jean recto azul', 'Zapatillas blancas'],
    match_percent: 88, occasion: 'oficina', season: 'otoño',
    ai_feedback: 'Combina: el blazer estructurado eleva el jean y las zapas mantienen el look relajado.',
    favorite: true, created_at: '2026-07-01T14:00:00Z', updated_at: '2026-07-01T14:00:00Z',
  },
  {
    id: 2,
    serial_key: 'CLUE-DEMO-0005-0005+CLUE-DEMO-0006-0006',
    name: 'Vestido rojo + Cartera mini',
    item_serials: ['CLUE-DEMO-0005-0005', 'CLUE-DEMO-0006-0006'],
    item_names: ['Vestido rojo satinado', 'Cartera mini negra'],
    match_percent: 76, occasion: 'fiesta', season: 'verano',
    ai_feedback: 'Combina: rojo + negro es un clásico de noche. Sumale calzado fino para cerrar el look.',
    favorite: false, created_at: '2026-07-03T21:00:00Z', updated_at: '2026-07-03T21:00:00Z',
  },
  {
    id: 3,
    serial_key: 'CLUE-DEMO-0007-0007+CLUE-DEMO-0008-0008',
    name: 'Buzo gris + Botas texanas',
    item_serials: ['CLUE-DEMO-0007-0007', 'CLUE-DEMO-0008-0008'],
    item_names: ['Buzo gris con capucha', 'Botas texanas marrones'],
    match_percent: 41, occasion: 'salidas', season: 'otoño',
    ai_feedback: 'No combina: el buzo deportivo choca con la energía boho de las texanas. Probá las texanas con denim.',
    favorite: false, created_at: '2026-07-06T18:30:00Z', updated_at: '2026-07-06T18:30:00Z',
  },
];
